version: "3.6"

services:
  test:
    image: cm-web-front:test
    environment:
      container_name: front
      PROFILES: dev
    ports:
      - "80:80"

# docker run -it -d --rm -p 80:80/tcp -e PROFILES:dev --name front cm-web-front:test