server:
  port: 7070

# spring:
#  mvc:
#    static-path-pattern: /static/**

---
spring:
  profiles: local
  application:
    name: cloud-svc-sample
  servlet:
    multipart:
      max-file-size: 15MB 
      max-request-size: 15MB

app.props:
  jwt:
    key-string: LcDVU5pmcXIakjK6yw/TJw==
    private-token-expiration: 43200
    part1: JwtPart1
    part2: JwtPart2
    access-token-expiration: 180
    refresh-token-expiration: 1800
    header: Authorization
    prefix: "Bearer "

logging:
  config: classpath:log4j2-spring.local.xml

cash.pg:
  clientKey: test_ck_ZORzdMaqN3wXJPGmEADV5AkYXQGw
  secretKey: test_sk_YyZqmkKeP8gGA7R464j8bQRxB9lG

datasource: 
  rcs:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #jdbc-url: jdbc:log4jdbc:mariadb://sandbox.ums-dev.uplus.co.kr:43306/cm_console?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    #jdbc-url: jdbc:log4jdbc:mariadb://sandbox.ums-dev.uplus.co.kr:43306/cm_console?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    #jdbc-url: jdbc:log4jdbc:mysql://mysql.ums-dev.uplus.co.kr:43306/cm_console?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    #username: cm_bo
    #password: ENC(YrccTPRMqk+u5utdFupqFIM3y2Nx+THl)
    jdbc-url: jdbc:log4jdbc:mysql://mysql.ums-qa.uplus.co.kr:43306/cm_console?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: cm_console
    password: ENC(Yb4RUow+7uw9BCzOckrD2N2Fo4S1YQk2)
    pool-name: hikari-cp
    maximum-pool-size: 30
    minimum-idle: 5
    connectionTimeout: 10000
    idleTimeout: 600000
    validationTimeout: 5000
    maxLifetime: 1800000
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true 
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true  
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
  continue-on-error: true
    
mongodb:
  #uri: mongodb://cloud:test1234@sandbox.ums-dev.uplus.co.kr:47017/cloud?authSource=cloud&authMechanism=SCRAM-SHA-256
  uri: mongodb://cm:test1234@mongo.ums-dev.uplus.co.kr:47017/cm?authSource=cm&authMechanism=SCRAM-SHA-256/cm?authSource=cloud&authMechanism=SCRAM-SHA-256
  database: cm
  connectionsPerHost: 30
  connectionsPerHostMin: 10
  maxWaitTime: 5000
  socketTimeout: 10000
  connectTimeout: 5000
      
---
spring:
  profiles: dev
  application:
    name: cloud-svc-sample
  mvc:
    contentnegotiation:
      favor-parameter: true
      favor-path-extension: true
      media-types:
        xls: application/vnd.ms-excel
  servlet:
    multipart:
      max-file-size: 15MB 
      max-request-size: 15MB
      
app.props:
  jwt:
    key-string: LcDVU5pmcXIakjK6yw/TJw==
    private-token-expiration: 1800
    part1: JwtPart1
    part2: JwtPart2
    access-token-expiration: 180
    refresh-token-expiration: 1800
    header: Authorization
    prefix: "Bearer "

logging:
  config: classpath:log4j2-spring.dev.xml

cash.pg:
  clientKey: test_ck_ZORzdMaqN3wXJPGmEADV5AkYXQGw
  secretKey: test_sk_YyZqmkKeP8gGA7R464j8bQRxB9lG

datasource: 
  rcs:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://dev-advmsg-db.cluster-crvzo9rgathe.ap-northeast-2.rds.amazonaws.com/cm_console?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: cm_console
    password: ENC(YrccTPRMqk+u5utdFupqFIM3y2Nx+THl)
    pool-name: hikari-cp
    maximum-pool-size: 30
    minimum-idle: 5
    connectionTimeout: 10000
    idleTimeout: 600000
    validationTimeout: 5000
    maxLifetime: 1800000
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true 
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true  
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
  continue-on-error: true
  
mongodb:
  uri: mongodb://cm:test1234@mongodb.default.svc.cluster.local:27017/cm?authSource=cm&authMechanism=SCRAM-SHA-256/cm?authSource=cloud&authMechanism=SCRAM-SHA-256
  database: cm
  connectionsPerHost: 30
  connectionsPerHostMin: 10
  maxWaitTime: 5000
  socketTimeout: 10000
  connectTimeout: 5000
    
---
spring:
  profiles: stg
  application:
    name: cloud-svc-sample
  servlet:
    multipart:
      max-file-size: 15MB 
      max-request-size: 15MB
    cookie:
      path: /
      
app.props:
  jwt:
    key-string: LcDVU5pmcXIakjK6yw/TJw==
    private-token-expiration: 1800
    part1: JwtPart1
    part2: JwtPart2
    access-token-expiration: 180
    refresh-token-expiration: 1800
    header: Authorization
    prefix: "Bearer "

logging:
  config: classpath:log4j2-spring.stg.xml

cash.pg:
  clientKey: test_ck_ZORzdMaqN3wXJPGmEADV5AkYXQGw
  secretKey: test_sk_YyZqmkKeP8gGA7R464j8bQRxB9lG

datasource: 
  rcs:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://stg-advmsg-db-cluster.cluster-crvzo9rgathe.ap-northeast-2.rds.amazonaws.com/cm_console?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: cm_console
    password: ENC(8yxau7b5v41ZqVEU3AGtQ5bQVNLB41ce)
    pool-name: hikari-cp
    maximum-pool-size: 30
    minimum-idle: 5
    connectionTimeout: 10000
    idleTimeout: 600000
    validationTimeout: 5000
    maxLifetime: 1800000
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true 
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true  
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
  continue-on-error: true
  
mongodb:
  uri: mongodb://cm:aptlwld123@mongodb.default.svc.cluster.local:27017/cm?authSource=cm&authMechanism=SCRAM-SHA-256
  database: cm
  connectionsPerHost: 30
  connectionsPerHostMin: 10
  maxWaitTime: 5000
  socketTimeout: 10000
  connectTimeout: 5000
    
---
spring:
  profiles: prd
  application:
    name: cloud-svc-sample
  servlet:
    multipart:
      max-file-size: 15MB 
      max-request-size: 15MB
      
app.props:
  jwt:
    key-string: LcDVU5pmcXIakjK6yw/TJw==
    private-token-expiration: 1800
    part1: JwtPart1
    part2: JwtPart2
    access-token-expiration: 180
    refresh-token-expiration: 1800
    header: Authorization
    prefix: "Bearer "

logging:
  config: classpath:log4j2-spring.prd.xml

cash.pg:
  clientKey: live_ck_d26DlbXAaV0eJJNjz6drqY50Q9RB
  secretKey: live_sk_XLkKEypNArWNmm5gmdXVlmeaxYG5

datasource: 
  rcs:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://prd-advmsg-db.cluster-ccrgfyulkkgg.ap-northeast-2.rds.amazonaws.com/cm_console?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: cm_console
    password: ENC(8yxau7b5v41ZqVEU3AGtQ5bQVNLB41ce)
    pool-name: hikari-cp
    maximum-pool-size: 30
    minimum-idle: 5
    connectionTimeout: 10000
    idleTimeout: 600000
    validationTimeout: 5000
    maxLifetime: 1800000
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true 
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true  
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
  continue-on-error: true
  
mongodb:
  uri: mongodb://cm:aptlwld123@mongodb.default.svc.cluster.local:27017/cm?authSource=cm&authMechanism=SCRAM-SHA-256
  database: cm
  connectionsPerHost: 30
  connectionsPerHostMin: 10
  maxWaitTime: 5000
  socketTimeout: 10000
  connectTimeout: 5000
  